name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 代码检出
      - name: Checkout repository
        uses: actions/checkout@v4

      # 生成时间戳环境变量
      - name: Generate build timestamp
        id: timestamp
        run: |
          echo "BUILD_TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      # 多平台构建环境设置
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker 登录
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 构建环境初始化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      # 多架构构建与推送 (关键修改点)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            moyan7864/chatnio:latest                # 修改点1
            moyan7864/chatnio:${{ steps.timestamp.outputs.BUILD_TIMESTAMP }}  # 修改点2
          cache-from: type=registry,ref=moyan7864/chatnio:buildcache  # 修改点3
          cache-to: type=registry,ref=moyan7864/chatnio:buildcache,mode=max  # 修改点4
